name: CI Workflow

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        auto-activate-base: false
        environment-file: environment.yaml
        activate-environment: myenv

    - name: Install the Package (Editable Mode)
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pip install -e .

    - name: Install Dependencies
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        conda info --envs
        conda list

    - name: Run Code Quality Checks
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        isort .
        black .
        flake8 .

    - name: Run Unit Tests
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate myenv
        pytest
